---
title: "GitHub test"
author: "Roberto Ruz Campos"
date: "23/6/2019"
output:
  html_document:
    df: paged
  github_document: default
---

This is my first GitHub experience!

Loaad required libraries
```{r, message=FALSE}
library(repurrrsive)
library(purrr)
library(magrittr)
library(tibble)
library(ggplot2)
library(dplyr)
library(viridis)
library(ggdark)
```

List all the GOT characters.
```{r}
my_characters <- map_chr(got_chars, "name")
my_characters
```

How many nicknames each character have?
```{r}
got <- set_names(got_chars, my_characters)
char_table <- got %>% 
  map_dbl(~length(.x[["aliases"]])) %>% 
  enframe()
char_table
```

Plot the results.
```{r, echo=FALSE}
order_vector <- char_table %>% 
  arrange(value) %>% 
  .$name
```


```{r Bar Chart, message=FALSE}
ggplot(char_table, aes(factor(name, level = order_vector), value)) +
  geom_col(aes(fill = factor(name, level = order_vector))) +
  ggtitle("Number of aliases of each character") +
  ylab("Number of aliases") + 
  xlab("Character Name") +
  scale_fill_viridis(discrete = TRUE) +
  dark_theme_light() +
  theme(legend.position = "none") +
  coord_flip()

```


The end.